services:
  postgres:
    image: postgres:16
    container_name: my-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - my-db-data:/var/lib/postgresql/data

volumes:
  my-db-data: